### ISSUE TITLE
Error when running apply_milpnet.py example

### ISSUE THREAD

**Issue by GalPerelman** [meghnathomas/MILPNet#2]
Hi
I tried to run the `apply_milpnet.py` example and got the following error:
`Traceback (most recent call last):
  File "C:\Users\User\Documents\GitHub\MILPNet\apply_milpnet.py", line 29, in <module>
    milpnet_results = run_gurobi(inp_file, no_ts, pump_on = False)
  File "C:\Users\User\Documents\GitHub\MILPNet\set_up_milpnet.py", line 689, in run_gurobi
    largest_q = max(np.max(results.link['flowrate']))
TypeError: 'numpy.float32' object is not iterable`

The error points to `set_up_milpnet.py` line 689:
`largest_q = max(np.max(results.link['flowrate']))`
`smallest_q = min(np.min(results.link['flowrate']))`

It seems like there is a redundant max function
Where the first `np.max` returns a float\int and then the outer `max` fails to find the maximum of a scalar 
Deleting the outer `max` and `min` solved this issue

**Comment by meghnathomas** [comment]
Hi @GalPerelman thanks for checking this out and raising this issue!

I am wondering if it is a package version issue, because the original code in `set_up_milpnet.py` runs fine for me. i.e., when I call `np.max(results.link['flowrate'])` I get the following output:

```
name
10     0.120466
11     0.082711
12     0.016268
21     0.014870
22     0.008971
31     0.003154
110    0.069399
111    0.033523
112    0.030980
113    0.006174
121    0.013248
122    0.006941
9      0.120466
dtype: float32
```

and require the additional `max()` in order to find the largest of these values. Can I ask what versions of numpy, pandas, and wntr you are using? Thanks!

**Comment by GalPerelman** [comment]
Hi @meghnathomas,
I used the following versions:
`numpy 1.25.0`
`pandas 2.0.3`
`wntr 1.0.0`

Please consider adding a `requirements.txt` file that holds the packages and versions dependencies for MILPNet

**Comment by meghnathomas** [comment]
Thanks for the suggestion! I've made a requirements.txt file but for now I haven't tested all compatible versions of the dependencies, I have only included the exact versions loaded on my machine that I know support the milpnet code.

**Comment by RecentConvert** [comment]
Hi there - I have the same issue. Do you plan to push your requirements.txt file? I would be happy to install the specific version of each dependency that you use.

**Comment by meghnathomas** [comment]
hi @RecentConvert! glad to see you are exploring MILPNet.

this is a link to the requirements.txt file --(https://github.com/meghnathomas/MILPNet/blob/master/requirements.txt)

are there other dependencies you are having trouble with?

**Comment by RecentConvert** [comment]
Thanks! I updated the dependencies using the requirements.txt. 

I'm having trouble with pandas. It's not listed in that file. The version I have installed (2.1.1) is incompatible with numpy==1.21.6.

Edit: I found an earlier version of pandas that works  (1.3.1). The code works now! Suggest adding pandas==1.3.1 to the Requirements file.

**Comment by meghnathomas** [comment]
Thank you for following up! The requirements.txt file has been updated now to include pandas
